<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="{{asset('public')}}/CLREnergy/dist/favicon.ico">
    <title>{{env('APP_NAME')}}</title>
    <link href="{{asset('public')}}/CLREnergy/dist/css/chunk-vendors.a9285ddb.css" rel="stylesheet">
    <link href="{{asset('public')}}/CLREnergy/dist/css/app.865ef51f.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('public')}}/CLREnergy/dist/css/806.88a93823.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <style>
        .van-overflow-hidden {
            overflow: unset !important;
        }

        marquee.banner_marquee_loop {
            height: 90px;
            margin-top: 20px;
        }

        marquee p {
            color: #fff;
        }
    </style>
</head>
<body class="van-overflow-hidden">
<div id="app" data-v-app="">
    <div>
        <div class="homepage" data-v-61186c26="">
            <div class="topclr flex" data-v-61186c26="">
                <div class="tiimgi" data-v-61186c26=""><img class="leftti"
                                                            src="{{asset('public')}}/CLREnergy/dist/img/7.38a3cd3e.png"
                                                            alt="" data-v-61186c26=""></div>
                <div class="rightimg" data-v-61186c26="" onclick="window.location.href='{{route('user.service')}}'"><img
                        src="{{asset('public/aaa.png')}}"
                        alt="" data-v-61186c26=""></div>
            </div>
            <div class="planbox flex" data-v-61186c26="">
                    <div class="lefti" data-v-61186c26=""><img
                        src="{{asset('public/uuu.png')}}"
                        alt="" data-v-61186c26="">
                    <div class="accounti" data-v-61186c26=""><p id="account_balance" data-v-61186c26="">{{price(auth()->user()->balance)}}</p><span
                            data-v-61186c26="">Account balance</span>
                    </div>
                </div>
                <div class="lefti" data-v-61186c26=""><img
                        src="{{asset('public/sss.png')}}"
                        alt="" data-v-61186c26="">
                    <?php
                    $totalDeposit = \App\Models\Deposit::where('user_id', auth()->id())->where('status', 'approved')->sum('amount');
                    ?>
                    <div class="accounti" data-v-61186c26=""><p data-v-61186c26="">{{price($totalDeposit)}}</p><span
                            data-v-61186c26="">Total Deposit</span>
                    </div>
                </div>
            </div>
<?php $p = \App\Models\Rebate::first(); ?>
<?php $c = \App\Models\Rebate::first(); ?>
            

            <div class="userbox" data-v-61186c26="">
                <img class="imgbell" src="{{asset('public/news.png')}}" alt="" data-v-61186c26="">
                <marquee behavior="" direction="" style="color: #fff;font-size: 13px;">
                   🏆 Welcome to register on CLR Energy app👑



 🛢Earn Daily Check-in Bonus $5.00💰



 ⛽ Get $2.00 bonus for every successful registration through your invitation, with a possible total bonus up to $60.00💰.



 🚀 Enjoy 20%, 2% and 1% team cashback for every investment your team makes.  💰



 ⚡ Earn 6%, 3%, and 1% team commissions for every income generated by your team.  
                </marquee>
            </div>
            <div class="van-swipe my-swipe" data-v-61186c26="">
                <div class="van-swipe__track"
                     style="transition-duration: 0ms; transform: translateX(0px); width: 418px;">
                    <div class="van-swipe-item" data-v-61186c26="" style="width: 418px;">
                        <div class="van-image imgsui" data-v-61186c26=""><img
                                src="{{asset('public')}}/c0541b944f11d991e975886d86dc9d7d.jpg"
                                class="van-image__img"></div>
                    </div>
                </div>
            </div>
            <div class="itembox" data-v-61186c26="">
                <div class="listit" data-v-61186c26="" onclick="window.location.href='{{route('user.deposit')}}'"><img
                        src="{{asset('public')}}/CLREnergy/dist/img/1.a523d763.png"
                        alt=""
                        data-v-61186c26="">
                    <p data-v-61186c26="">Deposit</p></div>
                <div class="listit" data-v-61186c26="" onclick="window.location.href='{{route('user.withdraw')}}'"><img
                        src="{{asset('public')}}/CLREnergy/dist/img/2.ee0852ad.png"
                        alt=""
                        data-v-61186c26="">
                    <p data-v-61186c26="">Withdraw</p></div>
                <div class="listit" data-v-61186c26="" onclick="window.location.href='{{route('user.bank')}}'"><img
                        src="{{asset('public')}}/CLREnergy/dist/img/3.d289cdb1.png"
                        alt=""
                        data-v-61186c26="">
                    <p data-v-61186c26="">Account</p></div>
                <div class="listit" data-v-61186c26="" onclick="window.location.href='{{route('user.rule')}}'"><img
                        src="{{asset('public')}}/CLREnergy/dist/img/4.976c4a80.png"
                        alt=""
                        data-v-61186c26="">
                    <p data-v-61186c26="">Guide</p></div>
            </div>
            <img onclick="window.location.href='{{route('task')}}'" class="imginvite"
                 src="{{asset('public')}}/CLREnergy/dist/img/2.26eeaa68.png" alt=""
                 data-v-61186c26="">
            <p class="dynamic" data-v-61186c26="">— Dynamic info —</p>
            <div class="warp-text" data-v-61186c26="">
                <marquee behavior="" direction="up" loop="" class="banner_marquee_loop" style="height: 200px;">
                    @for($i=0;$i<25;$i++)
                        <div class="list" data-v-61186c26="" style="margin-bottom: 1vw;">
                            <div class="lisit" data-v-61186c26=""><img src="{{asset('public/ck.png')}}" alt=""
                                                                           data-v-61186c26="">
                                    <p data-v-61186c26="">CLR-ENERGY User 212*******{{ mt_rand(1000,9999) }} successfully recharge {{ price(mt_rand(1,500)) }}</p>
                            </div>
                        </div>
                    @endfor
                </marquee>
            </div>
            <style>
                .textisboxi .list .imgpot[data-v-61186c26] {
                    padding-left: 0;
                    display: unset;
                }

                .textisboxi .list .imgpot img[data-v-61186c26] {
                    width: 40vw !important;
                    height: auto;
                    margin-right: 0vw;
                }

                .textisboxi .list[data-v-61186c26] {
                    padding: 12px 10px;
                }
            </style>
            <div class="checkini" data-v-61186c26=""
                 onclick="openCheckin()">
                <img src="{{asset('public')}}/CLREnergy/dist/img/check.33dbde01.png" alt=""
                     data-v-61186c26=""></div>
            <div class="van-overlay" role="button" tabindex="0" style="z-index: 2003;"></div>
            <div role="dialog" tabindex="0" class="van-popup van-popup--center newsbox" style="z-index: 2003;">
                <div class="innerlayer" data-v-61186c26=""><img class="topimg"
                                                                src="{{asset('public')}}/CLREnergy/dist/img/8.7638e6d2.png"
                                                                alt="" data-v-61186c26="">
                    <p class="title" data-v-61186c26="">Announcement</p>
                    <div class="cententi" data-v-61186c26="">
                        <div data-v-61186c26=""><p class="texti" data-v-61186c26="">
                        <p>🔥&nbsp;🏆 Welcome to register on CLR Energy app👑
💰.</p><p><br></p>
                    <p>🛢Earn Daily Check-in Bonus $0.010💰
.</p>
                    <p><br></p>
                    <p>⛽️&nbsp;⛽ Get $0.10 bonus for every successful registration through your invitation, with a possible total bonus up to $3.00💰.
</p>
                    <p><br></p>
                    <p>🚀&nbsp; 🚀 Enjoy 20%, 2% and 1% team cashback for every investment your team makes.  💰
.<span>💰</span></p>
                    <p><br></p>
                    <p>⚡ &nbsp;R
 ⚡ Earn 6%, 3%, and 1% team commissions for every income generated by your team.<span>💰</span>
                    </p><br>
                        </div>
                    </div>
                    <img class="imgclose"
                         onclick="document.querySelector('.van-overlay').style.display='none';document.querySelector('.newsbox').style.display='none';"
                         src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAAAXNSR0IArs4c6QAACVtJREFUaEPlm3nQ99UYxq/LvpUlJCKS1KBGC1GypVKRNkNIDd42JWUNWVOhF5neRoYkEpG8trIkYkSI7OuMnWTJXuIyn+b8Xuc97/f3+35/S3pm3DPPH89ztvv6nnPu5Tr3Y/2fiefBm2QfSYdL+qekl9v+zDzzjRub5GBJr5L0W0mH2f7ErOvMBDjJxpJOlfTQauG/S7q37Z/NqkzXuCRbSvqipBuW9kg60vYbZllnasBJDpN0vKRbdCy4ne3Pz6LIhN39kKTdmvZ/SLq97b9Ou9ZgwEluJemtkh4/ZhF2dmPbKLMwSfIRSbt0TLie7V9Pu9AgwEnWlfRhSVuNWeDLkp5i+7vTKtDXP8nWkj7KjlZ9z7P96L6xXe29gJPcRdKnJd2rYwKO1PMlnWL737MoMGRMkptK2lvSzpK+J+n1sxxn1poIOMkdJX0WY9Sh2Ncl7WP7B0OUXip9xgJOcjNJF0h6UIey55Qj/LelAmSoHpMAv13SUzsmeoukg67LIzxU+Vn6dQJOsp+k0zsmPE3S02zjC5ecJNlC0mMlfV/SWV2bsgbgJHeW9G1Jt24QnS9pV9v/WnJIJRVrjr3hKiKn296/1bUL8Psk7dV0/LGkLWxfuRTBolMS3OaulX6cQjboY7XOqwFOsl2xyvXfr5G0re0vLVWwBfC7JO3bsVGb2r569PcW8EWSAF3La20/bymDLYAfVrxKe2oPsX3KGoCTbCvpcw2wX5ZwsTdmTXJ/SQT6F9kmOPifS5L3S9qzWfjnkja0TUb338AjyXsJJJrOy2zjhiZKkh0knVcymquIt22v7BvX157kaElHScJ2HNE3Z5JNJX2jyqxGS6DP2asAJyFO5UsQwo2E3+9Zn/9xCiZ5B4FI1Q7oPW0TA88kSch/X1QNZofYKfQaK2M27gLbj6wBH0Q83MxytO3jhmhbduLYpi9Z0+Ns486mkiQvlfSyZhDucAPbv+gBvL2klohg7PpkV9de8CTsRJ19YJmZnDvcKyW4xy1wtGuBFHiM7U/1TlI6jPl4tL7ENrveK0mwIZAUtRxqe4WT3ETSHyXdvGq90PbDe2euOiSBEAB0O454G394Yd98SfAGkAutpT3B9gv6xo/aO64DTStt7w7gB0tqWYqjbC8fukC10C1L7sqxquUvnCDbrRdY1SfJsyWd2AF2uW0M12BJso2kLzQDMHzrAPgI8sumcUvbXx28wuo7DTPCveVD1vJnSTvZbhXhSj1T0kkdYE+y/axp9UhyI0m/k7R2M3ZzAEPGPaNq4N6tNU/MnISFPi7pgR1fecc6akuCwVzRARZS4ZBpwVanDdKCYKSWAwDcNlxqm6xjLklyG0nQqS0t9AdJj7L9lSRPl/RmSTdoFsP3HzhPVpbkjYVCrqdeDmB4qJrROMd2mzzMBD7JbSVhoYnCavl9AQo91IJdSAqahKvQUrkrAcziKDaSk21zpxYiSdYpMe5mAyY8Q9L+iyAXyiMB0WMtlwGYOzvKIWk83vYLByg3uEuSOxQi8D4TBr1NEqHsQvLtJBB+q6WGki4HMAvUx+oVtol0Fiol3h73RILbIhJaWL6dhHgATq6WawBMCFjH0MfZJmhfmCSB4iXwgE0ZJ4SDu9heCDGYZMfiHuv1rgIwD1Q1yb3C9qGLQptkwxLbrj9gTgwcoSjXbC5JwgvJe5pJrgAw/BVp1UjOtb3HXKuVwUnuXnZ2g2a+n5bf79axDv5793mfbMZY6e8AmDx2p2rhy2xvPi/gJIDhGN+jmes3hVUhQaG9/Rh0J5nZY0hqOk7PMX74fAAT0vEiOBJy2bXnXIznGcBs1Cj0J6If25fy93Lc6XfXDsV5NdxrxFRMuwEdARVTvAnAhJWEl7Vsbxt+a2pJsl4B26Zn0EQYJajUVZKEj0K013XHP1DYE07DYCkZIBFd+6S7DMD3k3RZM9sxtl85eIXSsbwyonxtE2gF7G7jUsQe0FAz+9oeDDrJQwr72kLYDMDkntwrgoORXGL7AdMAnhBcABbLy4cYKwU0frPreL+7vGUNCkqSvEbSc5vF8EbrjhiPlpOCxN7ENk8WvZKEVwqOahs+khKS/A+6HsWqA7o1dOjQ+ZLQKpeEIOonHVfkDNv7jQDvLuncZvDgEDPJMRS1NOMxUDt35b89O81d/uSYJ9qtbfP4Pumk4HHwPK3Ar31wBBiaBzawPtbQPvBaKD5RkpCV1Ik6ISJgL+4b29VergdxMDx3LTv08WNJCF4e0XGcCV2vXsUdjTn3g5jLQhMRGsI0kH1hjam8mVmSrFVO3Uh5XNk2k9xlEt6yoataTmzV60kNGGPxQ0ns9kjYXe7yr/o0L6BJ9smnJ3LHfXON2pPcWBJPt7iX02yTZHRKMb6cqNbY8q600aicqn1bgn1Y1sx4pu0nDVXy+uo3Jp5AnVNtHzjSqwVM0AADUpNfWOwn2m4D8esL2xrrFpcG6cg1qGWNE9r1Pgwl+rpmIEYIJvNHSwZlUaTUokD/tgaOHs+xDfW7SroAc28ukdQmEPhk3omvWCqgi8+Fxuni4Kgywo1d+2rYeaQrY7GJJPwdxHotWF645YUxE7N+vGKkTpZE4WkrRHdbdRXKTarioT4CBrEV3AM+9vJZlZ13XCHaKYPEgnfJAbapQlpD+grTumJSJuEu7237a/MqP+348rRLeQMUTpdMrFjoA0z7OztqJ1gIGuZI+OV5CPNpACfhzQp9uhIMpjpT0pMn6TOk1hIjxvFoC0ZGupIYHGz7W9MoP03fwm2fIOmADuJ+NBVg4bRXM1LtOr2AGVCsIczIOHKPXJUU7thF1nckuZ0kXhVhZNq6sRoLxuvwIQT+IMCjmZMAGL9W07r1wuSr5L2cCMjA3mKYdgeSUPkOp0zZI2Ri6ynqIdBRPO0CeJBMBbjsNvXLZ1Fv0bMCfDeBPD9YdqpuKVe4cnTHkgDmTtSSSIJ5IfgHLDvbJxTLPcE2McNgmRpwAc0bMOUH7DgZ0jRCXTX3jHGj/2OYZjzXhx198aRkYtyEMwGujvh9Jb26/E/CXHMNQExMT0kFKes3B/Tv7LIQJUtRGjE4IV79MDerXvU4rgYFZyeO6N15Jl0I4GrHeRqluA3gMIfjjFufzhgj3B1Az7ZN+cJCZKGAa42KQaK4BCOHQcLI8ZiGQRqdAnYPhoTyKIwQVXQYoYtnsfBDvsh1BnjI4tdHn/8ArUNtVL4YyZEAAAAASUVORK5CYII="
                         alt="" data-v-61186c26=""></div>
            </div>
            <div class="van-overlay" role="button" tabindex="0" style="z-index: 2002; display: none;"></div>
            <div role="dialog" tabindex="0" class="van-popup van-popup--center telegrami"
                 style="z-index: 2002; display: none;">
                <div class="teleis" data-v-61186c26=""><img class="imgte"
                                                            src="{{asset('public')}}/CLREnergy/dist/img/10.a00fd98e.png"
                                                            alt="" data-v-61186c26="">
                    <p class="channeli" data-v-61186c26="">Welfare channel</p>
                    <p class="learni" data-v-61186c26="">Learn about </p>
                    <p class="learni" data-v-61186c26="">channel information</p>
                    <div class="contact" data-v-61186c26=""><img
                            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAABGxJREFUWEftl21sU2UUx///e7vNvbD2dsJ0oiD0jqhAImqimJCAzpFpJPi2SJS9oLLbkX1wBOK3fSFblohEts5F4hIxhGDUL2qMRiGaGBMxcSKZtB2LCSHGbbddtkwH7T3m7s2uW3e7Fggf6Kem5/z/z6/nOee5zyVusg9vMh7cAkrcEU/PgIfjsV0kaiDYYBFtN75CInR3hZ5QwDoCOwHkJ0CO3jAgT8fFVVDjtRTWErJ6od4VYOj6AvUM3KaNWztJqRfINgLKokNEfHNdgNyB8EOKSD2Ilwlo6U6yUA5dM6BlHZdKVI6/QqKe4MYUECKCE0L8owCvJedYwI7sgF48pWpbNz1FSJ0AzxLIS10NXrAoDbhqRRSX8iWAsjm5pEy4lDszAiruDPtUBbW0pAbEysW2RIAJCtrMOFo9KjcrlM8AuBfQ/Gn69dXpA3VfLvDExl+wGxTAFsL5UBXgTAxqw6h/zQVvV+glEXyYsorkKdPwVTsCFQcGHlUlVk+iGkBxOg1qj69ADkT95T12fklXuMmy5B0y9ZRZ5P6o4Xt7QaDCIxdL83KsV0GpA3B/OhDTOSLA8Zha2Dy6t2wIALVAqJXAQScPgbUl4l/3w/9ALaddnhUrqyiwx7WKQI6Tydw4g3HCGDF8303+3n02R4u7jxHY7eQjIrGIq8iNvWXjdAd+0xTk7ydg98YdTuLk+FTTSrsZ5yE06ROT8c7zRRpyPyaxPR0/gfwa8Zc/aOfaJT1HYH06wnkwIt8rQMNwY3nfTKyoq3dFrhR+Dsgj6XoK2R0xfA2TQN6u8BER8S9liwQYFuJA1PD1AJSZhd2B4BoV/AqAni7MZB6xxzT0D6a+AljW0VeiMudphdgBsSpBFqYwFAE/uhqT5rEmfTAxx90R2qQq/AKQJW87XFhvvqGfnwWas/jhH/O1vOVP0oYjn4FI6VScobhFY2Tf2m+TYd0dwQpV4Sf2f1tSZaaSR82/fR600FoYKNGxRRSttP8xxGVjpNDVg7p7/01eUAv07wKsHgK5GcBAgNMRv75tRut4MC62iLcr3Cwi7Y7XikVMRNAWadTfyhpIC4Ts66bjgedUNYvWc1Fjnf18m+5vJ0WKuBYIDhK8PUP5rEzJy7traM89l7MEEmqB8BUCrqyAiEumod+d6JFRD2nd/W7GrWhWMJNi+dT0lz+fNdD0AdifBDQGsBeQx9MFFZGDkcby9uyBjv7xsKqqPycYjUBYZQ6u/UlbHrInpoWk43ZaxNaooZ/JHui9YIVq8evJoosMW1QqR/y+X2aMvZ3hzUI5QWBVqmoJEI/IFQ8aHxjLGsjbGa4G5STAv4SoiBi+35MXtm8RKvLfBzCnR2bzBOfMRn3ey0BmTd0Z8kPBm7F4rGp0333BxXpGC/Q3ENbhpDdUW3LM9OuvJ2szAvK+Gyo2Td84WhhLp4G1o30bqLpOJt4+LWJ31NCPXxOgdCDm5XSfLfDGiluFrIFIb6Qgp3KhZ2NGFcoIKE3RLSCnQv0H9fZ/w0PDaD8AAAAASUVORK5CYII="
                            alt="" data-v-61186c26="">
                        <p data-v-61186c26="">Contact</p></div>
                    <img class="imgcolse"
                         src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAAAXNSR0IArs4c6QAACVtJREFUaEPlm3nQ99UYxq/LvpUlJCKS1KBGC1GypVKRNkNIDd42JWUNWVOhF5neRoYkEpG8trIkYkSI7OuMnWTJXuIyn+b8Xuc97/f3+35/S3pm3DPPH89ztvv6nnPu5Tr3Y/2fiefBm2QfSYdL+qekl9v+zDzzjRub5GBJr5L0W0mH2f7ErOvMBDjJxpJOlfTQauG/S7q37Z/NqkzXuCRbSvqipBuW9kg60vYbZllnasBJDpN0vKRbdCy4ne3Pz6LIhN39kKTdmvZ/SLq97b9Ou9ZgwEluJemtkh4/ZhF2dmPbKLMwSfIRSbt0TLie7V9Pu9AgwEnWlfRhSVuNWeDLkp5i+7vTKtDXP8nWkj7KjlZ9z7P96L6xXe29gJPcRdKnJd2rYwKO1PMlnWL737MoMGRMkptK2lvSzpK+J+n1sxxn1poIOMkdJX0WY9Sh2Ncl7WP7B0OUXip9xgJOcjNJF0h6UIey55Qj/LelAmSoHpMAv13SUzsmeoukg67LIzxU+Vn6dQJOsp+k0zsmPE3S02zjC5ecJNlC0mMlfV/SWV2bsgbgJHeW9G1Jt24QnS9pV9v/WnJIJRVrjr3hKiKn296/1bUL8Psk7dV0/LGkLWxfuRTBolMS3OaulX6cQjboY7XOqwFOsl2xyvXfr5G0re0vLVWwBfC7JO3bsVGb2r569PcW8EWSAF3La20/bymDLYAfVrxKe2oPsX3KGoCTbCvpcw2wX5ZwsTdmTXJ/SQT6F9kmOPifS5L3S9qzWfjnkja0TUb338AjyXsJJJrOy2zjhiZKkh0knVcymquIt22v7BvX157kaElHScJ2HNE3Z5JNJX2jyqxGS6DP2asAJyFO5UsQwo2E3+9Zn/9xCiZ5B4FI1Q7oPW0TA88kSch/X1QNZofYKfQaK2M27gLbj6wBH0Q83MxytO3jhmhbduLYpi9Z0+Ns486mkiQvlfSyZhDucAPbv+gBvL2klohg7PpkV9de8CTsRJ19YJmZnDvcKyW4xy1wtGuBFHiM7U/1TlI6jPl4tL7ENrveK0mwIZAUtRxqe4WT3ETSHyXdvGq90PbDe2euOiSBEAB0O454G394Yd98SfAGkAutpT3B9gv6xo/aO64DTStt7w7gB0tqWYqjbC8fukC10C1L7sqxquUvnCDbrRdY1SfJsyWd2AF2uW0M12BJso2kLzQDMHzrAPgI8sumcUvbXx28wuo7DTPCveVD1vJnSTvZbhXhSj1T0kkdYE+y/axp9UhyI0m/k7R2M3ZzAEPGPaNq4N6tNU/MnISFPi7pgR1fecc6akuCwVzRARZS4ZBpwVanDdKCYKSWAwDcNlxqm6xjLklyG0nQqS0t9AdJj7L9lSRPl/RmSTdoFsP3HzhPVpbkjYVCrqdeDmB4qJrROMd2mzzMBD7JbSVhoYnCavl9AQo91IJdSAqahKvQUrkrAcziKDaSk21zpxYiSdYpMe5mAyY8Q9L+iyAXyiMB0WMtlwGYOzvKIWk83vYLByg3uEuSOxQi8D4TBr1NEqHsQvLtJBB+q6WGki4HMAvUx+oVtol0Fiol3h73RILbIhJaWL6dhHgATq6WawBMCFjH0MfZJmhfmCSB4iXwgE0ZJ4SDu9heCDGYZMfiHuv1rgIwD1Q1yb3C9qGLQptkwxLbrj9gTgwcoSjXbC5JwgvJe5pJrgAw/BVp1UjOtb3HXKuVwUnuXnZ2g2a+n5bf79axDv5793mfbMZY6e8AmDx2p2rhy2xvPi/gJIDhGN+jmes3hVUhQaG9/Rh0J5nZY0hqOk7PMX74fAAT0vEiOBJy2bXnXIznGcBs1Cj0J6If25fy93Lc6XfXDsV5NdxrxFRMuwEdARVTvAnAhJWEl7Vsbxt+a2pJsl4B26Zn0EQYJajUVZKEj0K013XHP1DYE07DYCkZIBFd+6S7DMD3k3RZM9sxtl85eIXSsbwyonxtE2gF7G7jUsQe0FAz+9oeDDrJQwr72kLYDMDkntwrgoORXGL7AdMAnhBcABbLy4cYKwU0frPreL+7vGUNCkqSvEbSc5vF8EbrjhiPlpOCxN7ENk8WvZKEVwqOahs+khKS/A+6HsWqA7o1dOjQ+ZLQKpeEIOonHVfkDNv7jQDvLuncZvDgEDPJMRS1NOMxUDt35b89O81d/uSYJ9qtbfP4Pumk4HHwPK3Ar31wBBiaBzawPtbQPvBaKD5RkpCV1Ik6ISJgL+4b29VergdxMDx3LTv08WNJCF4e0XGcCV2vXsUdjTn3g5jLQhMRGsI0kH1hjam8mVmSrFVO3Uh5XNk2k9xlEt6yoataTmzV60kNGGPxQ0ns9kjYXe7yr/o0L6BJ9smnJ3LHfXON2pPcWBJPt7iX02yTZHRKMb6cqNbY8q600aicqn1bgn1Y1sx4pu0nDVXy+uo3Jp5AnVNtHzjSqwVM0AADUpNfWOwn2m4D8esL2xrrFpcG6cg1qGWNE9r1Pgwl+rpmIEYIJvNHSwZlUaTUokD/tgaOHs+xDfW7SroAc28ukdQmEPhk3omvWCqgi8+Fxuni4Kgywo1d+2rYeaQrY7GJJPwdxHotWF645YUxE7N+vGKkTpZE4WkrRHdbdRXKTarioT4CBrEV3AM+9vJZlZ13XCHaKYPEgnfJAbapQlpD+grTumJSJuEu7237a/MqP+348rRLeQMUTpdMrFjoA0z7OztqJ1gIGuZI+OV5CPNpACfhzQp9uhIMpjpT0pMn6TOk1hIjxvFoC0ZGupIYHGz7W9MoP03fwm2fIOmADuJ+NBVg4bRXM1LtOr2AGVCsIczIOHKPXJUU7thF1nckuZ0kXhVhZNq6sRoLxuvwIQT+IMCjmZMAGL9W07r1wuSr5L2cCMjA3mKYdgeSUPkOp0zZI2Ri6ynqIdBRPO0CeJBMBbjsNvXLZ1Fv0bMCfDeBPD9YdqpuKVe4cnTHkgDmTtSSSIJ5IfgHLDvbJxTLPcE2McNgmRpwAc0bMOUH7DgZ0jRCXTX3jHGj/2OYZjzXhx198aRkYtyEMwGujvh9Jb26/E/CXHMNQExMT0kFKes3B/Tv7LIQJUtRGjE4IV79MDerXvU4rgYFZyeO6N15Jl0I4GrHeRqluA3gMIfjjFufzhgj3B1Az7ZN+cJCZKGAa42KQaK4BCOHQcLI8ZiGQRqdAnYPhoTyKIwQVXQYoYtnsfBDvsh1BnjI4tdHn/8ArUNtVL4YyZEAAAAASUVORK5CYII="
                         alt="" data-v-61186c26=""></div>
            </div>


            <style>
                [data-v-61186c26] .singreward {
                    width: 78.133333vw;
                    height: 85.066667vw;
                    background: url({{asset('public')}}/CLREnergy/dist/img/9.1102355e.png) no-repeat;
                    background-size: cover;
                    padding: 18.133333vw 13.333333vw 5.333333vw;
                }
            </style>
                <?php
                    $setting = \App\Models\Setting::first();
                    $settingCheckin = $setting ? $setting->checkin : 0;
                    $displayCheckin = auth()->user()->checkin > 0 ? auth()->user()->checkin : ($settingCheckin > 0 ? $settingCheckin : 0.01);
                ?>
                <div class="van-overlay checkin" role="button" tabindex="0" style="z-index: 2010;display: none;" onclick="checkInStopPropositionLayler()"></div>
                <div role="dialog" tabindex="0" class="van-popup van-popup--center singreward"
                      onclick="checkInStopPropositionBox(event)"
                      style="z-index: 2010;display: none;"><p
                          class="rewardi" data-v-61186c26="">+{{price($displayCheckin)}}</p>
                <p class="titleter" data-v-61186c26="">Daily Check Bonus</p>
                <p class="btnnow" data-v-61186c26=""
                   onclick="submitCheckin()">
                    Receive now</p></div>

            @include('app.layout.manu')
        </div>
    </div>
    <div class="xuanfu" draggable="true" id="moveDiv" onclick="window.location.href='{{route('user.service')}}'">
        <div class="seruis"><img class="" src="{{asset('public')}}/CLREnergy/dist/img/online.86e72dea.png" alt=""></div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
@include('alert-message')
<script>
    function openCheckin() {
        document.querySelector('.checkin').style.zIndex = '2002';
        document.querySelector('.checkin').style.display = 'block';
        document.querySelector('.singreward').style.zIndex = '2002';
        document.querySelector('.singreward').style.display = 'block';
    }

    function checkInStopPropositionLayler(){
        document.querySelector('.checkin').style.zIndex = '-1';
        document.querySelector('.checkin').style.display = 'none';
        document.querySelector('.singreward').style.zIndex = '-1';
        document.querySelector('.singreward').style.display = 'none';
    }

    function checkInStopPropositionBox(event){
        event.stopPropagation()
    }

    function submitCheckin(){
        $.ajax({
            url: '{{route('checkin')}}',
            dataType: 'json',
            type: 'GET',
            error: function(error) {
                console.log(error)
            },
            success: function(data) {
                message(data.message);
                // update account balance in UI if returned
                if (data.new_balance_formatted) {
                    var el = document.querySelector('#account_balance');
                    if (el) el.textContent = data.new_balance_formatted;
                }
                // update reward display to zero or hide amount
                if (data.amount_formatted) {
                    var rewardEl = document.querySelector('.rewardi');
                    if (rewardEl) rewardEl.textContent = '+' + data.amount_formatted;
                }
                document.querySelector('.checkin').style.zIndex='-1';
                document.querySelector('.singreward').style.zIndex='-1';
            },
        });
    }
</script>
</body>
</html>
